version: 'Build {build}'

skip_tags: true

image: Visual Studio 2015
configuration: Release
platform: Any CPU

cache:
  - packages -> **\packages.config

before_build:
- ps: >-
    $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
    
    ($env:APPVEYOR_REPO_NAME) >> VERSION
    
    ($env:APPVEYOR_REPO_BRANCH) >> VERSION
    
    ($env:GIT_HASH) >> VERSION
    
    ($env:APPVEYOR_BUILD_VERSION) >> VERSION
    
    ($env:APPVEYOR_REPO_COMMIT_TIMESTAMP) >> VERSION
    
- appveyor-retry nuget restore

build:
  project: XIVLauncher.sln
  verbosity: minimal

after_build:
- cmd: >-
    7z a XIVLauncher-%APPVEYOR_REPO_BRANCH%-b%APPVEYOR_BUILD_NUMBER%-%GIT_HASH%.zip .\XIVLauncher\bin\Release\* -mx=7

artifacts:
- path: XIVLauncher-$(APPVEYOR_REPO_BRANCH)-b$(APPVEYOR_BUILD_NUMBER)-$(GIT_HASH).zip
  name: XIVLauncher

deploy:
- provider: GitHub
  release: $(APPVEYOR_BUILD_VERSION)
  description: ""
  artifact: XIVLauncher
  auth_token:
   secure: sK0IFC1Nr/kDN0C3RsPwe/uLR9/5ZxVhpXuosQxarP5QRNV4xKyDRAJY4PJBgsbu
